default_context:
  project_name: "Puzzle Massive"
  project_slug: "puzzle-massive"
  site_domain: "puzzle.massive.xyz"
  s3_object_storage_name: "puzzle.massive.xyz"
  site_protocol: "http"
  internal_port_prefix: "63"
  full_name: "Jake Hickenlooper"
  email: "jake@weboftomorrow.com"
  project_short_description: "Puzzle Massive is a Massively Multiplayer Online Jigsaw Puzzle web application. Jigsaw puzzles are made from randomly generated classic interlocking pieces and can be 5000+ pieces.  Players can collaborate on the same jigsaw puzzle in real time.  Other player's piece movements are moderated automatically in order to prevent abusive behavior."
  version: "2.0.0"
  now: "2018-09-28"
  generated_by_cookiecutter_website_version: "0.1.0"
