---
#https://docs.ansible.com/ansible/latest/collections/ansible/posix/synchronize_module.html#ansible-collections-ansible-posix-synchronize-module

- name: Synchronize Puzzle Massive resources directory from local
  hosts: legacy_puzzle_massive
  user: dev
  tasks:

    - name: Synchronize resources directory from local
      ansible.posix.synchronize:
        src: "{{ resources_directory }}"
        dest: /srv/puzzle-massive/
